# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Updatecli < Formula
  desc "Continuously update everything."
  homepage "https://updatecli.io/"
  version "0.11.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/updatecli/updatecli/releases/download/v0.11.0/updatecli_Darwin_arm64.tar.gz"
      sha256 "5ac298c4c0e0c26270dcce3832490839560bc245749c7ad9f99f788c09cfe011"

      def install
        bin.install "updatecli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/updatecli/updatecli/releases/download/v0.11.0/updatecli_Darwin_x86_64.tar.gz"
      sha256 "abb9624c900602d75f6ddd3b900eb84dd18e4e8545a754a9269742c9b4b3018c"

      def install
        bin.install "updatecli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/updatecli/updatecli/releases/download/v0.11.0/updatecli_Linux_arm64.tar.gz"
      sha256 "40c17d19f39b5d7ea12c7f26c9330ec9d55c5f3e04c9a5ddfa13969486210798"

      def install
        bin.install "updatecli"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/updatecli/updatecli/releases/download/v0.11.0/updatecli_Linux_armv6.tar.gz"
      sha256 "06183a0b81019a6797b490f95995a10b318a1882c83059d79818a31eb0d345c8"

      def install
        bin.install "updatecli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/updatecli/updatecli/releases/download/v0.11.0/updatecli_Linux_x86_64.tar.gz"
      sha256 "9d20bdc87c5ec7aba1b9b6d97f1e9ebe2bdbd512e344f428b4dad9d52491903e"

      def install
        bin.install "updatecli"
      end
    end
  end

  test do
    system "#{bin}/updatecli version"
  end
end
