# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Updatecli < Formula
  desc "Continuously update everything."
  homepage "https://updatecli.io/"
  version "0.22.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/updatecli/updatecli/releases/download/v0.22.3/updatecli_Darwin_x86_64.tar.gz"
      sha256 "b3dcb9c5ff970f849f51f440d8a5bd26c2132b2d827ba362ad8fe6bb497d29be"

      def install
        bin.install "updatecli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/updatecli/updatecli/releases/download/v0.22.3/updatecli_Darwin_arm64.tar.gz"
      sha256 "fec8f281c1fe785e30ad0975adbedabd9af28418116120248ff64ae434c0989a"

      def install
        bin.install "updatecli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/updatecli/updatecli/releases/download/v0.22.3/updatecli_Linux_x86_64.tar.gz"
      sha256 "107298a354b1b30b33e610d0d99d59666cdf5fe115c6321283b1eb1cba04165a"

      def install
        bin.install "updatecli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/updatecli/updatecli/releases/download/v0.22.3/updatecli_Linux_arm64.tar.gz"
      sha256 "05b3266c778d36c16105fac3dd302f6a32d3c19aec1a36d930656a4552338f16"

      def install
        bin.install "updatecli"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/updatecli/updatecli/releases/download/v0.22.3/updatecli_Linux_armv6.tar.gz"
      sha256 "e7526809ca8ec5d01a8320226a3386a1ad087ed22973ec75e60be76f654fdb0c"

      def install
        bin.install "updatecli"
      end
    end
  end

  test do
    system "#{bin}/updatecli version"
  end
end
